// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/product.proto

package appproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Product struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type AddProductReq struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductReq) Reset()         { *m = AddProductReq{} }
func (m *AddProductReq) String() string { return proto.CompactTextString(m) }
func (*AddProductReq) ProtoMessage()    {}
func (*AddProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{1}
}

func (m *AddProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductReq.Unmarshal(m, b)
}
func (m *AddProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductReq.Marshal(b, m, deterministic)
}
func (m *AddProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductReq.Merge(m, src)
}
func (m *AddProductReq) XXX_Size() int {
	return xxx_messageInfo_AddProductReq.Size(m)
}
func (m *AddProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductReq proto.InternalMessageInfo

func (m *AddProductReq) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type AddProductResp struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddProductResp) Reset()         { *m = AddProductResp{} }
func (m *AddProductResp) String() string { return proto.CompactTextString(m) }
func (*AddProductResp) ProtoMessage()    {}
func (*AddProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{2}
}

func (m *AddProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddProductResp.Unmarshal(m, b)
}
func (m *AddProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddProductResp.Marshal(b, m, deterministic)
}
func (m *AddProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddProductResp.Merge(m, src)
}
func (m *AddProductResp) XXX_Size() int {
	return xxx_messageInfo_AddProductResp.Size(m)
}
func (m *AddProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddProductResp proto.InternalMessageInfo

func (m *AddProductResp) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetProductsReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductsReq) Reset()         { *m = GetProductsReq{} }
func (m *GetProductsReq) String() string { return proto.CompactTextString(m) }
func (*GetProductsReq) ProtoMessage()    {}
func (*GetProductsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{3}
}

func (m *GetProductsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsReq.Unmarshal(m, b)
}
func (m *GetProductsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsReq.Marshal(b, m, deterministic)
}
func (m *GetProductsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsReq.Merge(m, src)
}
func (m *GetProductsReq) XXX_Size() int {
	return xxx_messageInfo_GetProductsReq.Size(m)
}
func (m *GetProductsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsReq proto.InternalMessageInfo

type GetProductsResp struct {
	Products             []*Product `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetProductsResp) Reset()         { *m = GetProductsResp{} }
func (m *GetProductsResp) String() string { return proto.CompactTextString(m) }
func (*GetProductsResp) ProtoMessage()    {}
func (*GetProductsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{4}
}

func (m *GetProductsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductsResp.Unmarshal(m, b)
}
func (m *GetProductsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductsResp.Marshal(b, m, deterministic)
}
func (m *GetProductsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductsResp.Merge(m, src)
}
func (m *GetProductsResp) XXX_Size() int {
	return xxx_messageInfo_GetProductsResp.Size(m)
}
func (m *GetProductsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductsResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductsResp proto.InternalMessageInfo

func (m *GetProductsResp) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type GetProductReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductReq) Reset()         { *m = GetProductReq{} }
func (m *GetProductReq) String() string { return proto.CompactTextString(m) }
func (*GetProductReq) ProtoMessage()    {}
func (*GetProductReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{5}
}

func (m *GetProductReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductReq.Unmarshal(m, b)
}
func (m *GetProductReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductReq.Marshal(b, m, deterministic)
}
func (m *GetProductReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductReq.Merge(m, src)
}
func (m *GetProductReq) XXX_Size() int {
	return xxx_messageInfo_GetProductReq.Size(m)
}
func (m *GetProductReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductReq proto.InternalMessageInfo

func (m *GetProductReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetProductResp struct {
	Product              *Product `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProductResp) Reset()         { *m = GetProductResp{} }
func (m *GetProductResp) String() string { return proto.CompactTextString(m) }
func (*GetProductResp) ProtoMessage()    {}
func (*GetProductResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cfd9ed8e6077aee0, []int{6}
}

func (m *GetProductResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProductResp.Unmarshal(m, b)
}
func (m *GetProductResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProductResp.Marshal(b, m, deterministic)
}
func (m *GetProductResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProductResp.Merge(m, src)
}
func (m *GetProductResp) XXX_Size() int {
	return xxx_messageInfo_GetProductResp.Size(m)
}
func (m *GetProductResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProductResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetProductResp proto.InternalMessageInfo

func (m *GetProductResp) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "appproto.Product")
	proto.RegisterType((*AddProductReq)(nil), "appproto.AddProductReq")
	proto.RegisterType((*AddProductResp)(nil), "appproto.AddProductResp")
	proto.RegisterType((*GetProductsReq)(nil), "appproto.GetProductsReq")
	proto.RegisterType((*GetProductsResp)(nil), "appproto.GetProductsResp")
	proto.RegisterType((*GetProductReq)(nil), "appproto.GetProductReq")
	proto.RegisterType((*GetProductResp)(nil), "appproto.GetProductResp")
}

func init() { proto.RegisterFile("proto/product.proto", fileDescriptor_cfd9ed8e6077aee0) }

var fileDescriptor_cfd9ed8e6077aee0 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xcf, 0x4f, 0xfa, 0x30,
	0x14, 0xff, 0x0e, 0xbe, 0x11, 0x7c, 0x84, 0xa9, 0xcf, 0x83, 0x95, 0x8b, 0xa4, 0x27, 0xa2, 0x61,
	0x8b, 0x78, 0x54, 0x13, 0x31, 0x26, 0x1e, 0x35, 0xf3, 0x62, 0xbc, 0x8d, 0xb6, 0xc1, 0x26, 0x40,
	0x4b, 0xdb, 0xf1, 0xd7, 0xfa, 0xc7, 0x18, 0xea, 0xe6, 0x3a, 0x83, 0x07, 0x4f, 0x6d, 0xdf, 0xe7,
	0x57, 0xdf, 0x07, 0x8e, 0xb5, 0x51, 0x4e, 0xa5, 0xda, 0x28, 0x5e, 0x30, 0x97, 0xf8, 0x17, 0x76,
	0x73, 0xad, 0xfd, 0x8d, 0x3e, 0x41, 0xe7, 0xf9, 0x0b, 0xc2, 0x18, 0x5a, 0x92, 0x93, 0x68, 0x18,
	0x8d, 0xda, 0x59, 0x4b, 0x72, 0x44, 0xf8, 0xbf, 0xca, 0x97, 0x82, 0xb4, 0x86, 0xd1, 0x68, 0x3f,
	0xf3, 0x77, 0x1c, 0x42, 0x8f, 0x0b, 0xcb, 0x8c, 0xd4, 0x4e, 0xaa, 0x15, 0x69, 0x7b, 0x28, 0x1c,
	0xd1, 0x1b, 0xe8, 0x4f, 0x39, 0x2f, 0x3d, 0x33, 0xb1, 0xc6, 0x0b, 0xe8, 0x94, 0xe1, 0xde, 0xbb,
	0x37, 0x39, 0x4a, 0xaa, 0xf4, 0xa4, 0xa2, 0x55, 0x0c, 0x7a, 0x0e, 0x71, 0xa8, 0xb6, 0x1a, 0x09,
	0x74, 0x6c, 0xc1, 0x98, 0xb0, 0xd6, 0xcb, 0xbb, 0x59, 0xf5, 0xa4, 0x87, 0x10, 0x3f, 0x0a, 0x57,
	0x72, 0x6d, 0x26, 0xd6, 0xf4, 0x0e, 0x0e, 0x1a, 0x13, 0xab, 0x71, 0x0c, 0xdd, 0xd2, 0x7b, 0xab,
	0x6f, 0xef, 0x8e, 0xff, 0xa6, 0xd0, 0x33, 0xe8, 0xd7, 0x0e, 0xdb, 0xdf, 0xff, 0x28, 0x85, 0xde,
	0x86, 0xa1, 0x3e, 0xe1, 0x2f, 0xfb, 0x4d, 0x3e, 0x22, 0x88, 0xcb, 0xe1, 0x8b, 0x30, 0x1b, 0xc9,
	0x04, 0x4e, 0x01, 0xea, 0x95, 0xf1, 0xa4, 0x16, 0x37, 0x6a, 0x1c, 0x90, 0xdd, 0x80, 0xd5, 0xf4,
	0x1f, 0x3e, 0x40, 0x2f, 0xd8, 0x1b, 0x03, 0x6a, 0xb3, 0xa0, 0xc1, 0xe9, 0x2f, 0x88, 0x77, 0x99,
	0x02, 0xd4, 0xc3, 0xf0, 0x23, 0x8d, 0x46, 0x06, 0x64, 0x37, 0xb0, 0xb5, 0xb8, 0xbf, 0x7c, 0x4b,
	0xe7, 0xd2, 0xbd, 0x17, 0xb3, 0x84, 0xa9, 0x65, 0xfa, 0x9a, 0xaf, 0x36, 0x32, 0x5f, 0xa4, 0xae,
	0x70, 0xca, 0xc8, 0x7c, 0x31, 0x9e, 0x1b, 0xcd, 0x52, 0x2f, 0xbd, 0xae, 0x3c, 0x66, 0x7b, 0xfe,
	0xb8, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x59, 0x2c, 0xc5, 0xa8, 0x02, 0x00, 0x00,
}
